version: "3.7"

services:
  app:
    image: "node:latest"
    command: bash -c "yarn && NODE_OPTIONS=--inspect yarn dev"
    working_dir: "/var/app"
    volumes:
      - ./assets:/var/app/assets
      - ./components:/var/app/components
      - ./config:/var/app/config
      - ./contexts:/var/app/contexts
      - ./hooks:/var/app/hooks
      - ./layout:/var/app/layout
      - ./lib:/var/app/lib
      - ./modules:/var/app/modules
      - ./pages:/var/app/pages
      - ./public:/var/app/public
      - ./styles:/var/app/styles
      - ./.babelrc:/var/app/.babelrc
      - ./.npmrc:/var/app/.npmrc
      - ./next.config.js:/var/app/next.config.js
      - ./next-env.d.ts:/var/app/next-env.d.ts
      - ./package.json:/var/app/package.json
      - ./postcss.config.js:/var/app/postcss.config.js
      - ./tailwind.config.js:/var/app/tailwind.config.js
      - ./tsconfig.json:/var/app/tsconfig.json
      - node-modules:/var/app/node_modules
    tmpfs:
      - /var/app/.next
    ports:
      - "${APP_PORT:-3000}:3000"
      - "${DEBUG_PORT:-9229}:9229"
    environment:
      FONTAWESOME_NPM_AUTH_TOKEN: "${FONTAWESOME_NPM_AUTH_TOKEN}"

volumes:
  node-modules: {}
